name: CD - Deploy to Elastic Beanstalk
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3
      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Set up AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      # Generate Timestamp
      - name: Generate Timestamp
        run: echo "BUILD_TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      # Build JAR with Maven
      - name: Build with Maven
        run: mvn clean package --batch-mode -q
        env:
          SPRING_PROFILES_ACTIVE: dev
          DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      # Rename JAR for Consistency
      - name: Rename JAR
        run: |
          mv target/*.jar target/DEV-v${BUILD_TIMESTAMP}.jar

      # Upload to S3 Dev bucket artifact for build file
      - name: Upload to S3
        run: aws s3 cp target/DEV-v${BUILD_TIMESTAMP}.jar s3://${{ secrets.DEV_BUCKET_NAME }}/artifact-build/DEV-v${BUILD_TIMESTAMP}.jar



      # Create Elastic Beanstalk Application Version
      - name: Create Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name "TWDevJobs-dev" \
          --version-label "TWDevJobs-dev-${BUILD_TIMESTAMP}" \
          --source-bundle S3Bucket=${{ secrets.DEV_BUCKET_NAME }},S3Key=artifact-build/DEV-v${BUILD_TIMESTAMP}.jar

      - name: Update Elastic Beanstalk Environment
        run: |
          aws elasticbeanstalk update-environment \
          --environment-name "TWDevJobs-dev-env" \
          --version-label "twdevjobs-dev-${BUILD_TIMESTAMP}"