name: Build and Test CI
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3
      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      # Build and Test with Maven
      - name: Build with Maven
        run: mvn clean package -q --batch-mode
        env:
          SPRING_PROFILES_ACTIVE: test
          AWS_ACCESS_KEYID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET: ${{ secrets.DEV_BUCKET_NAME }}

      # Run Tests
      - name: Run Tests
        run: mvn test
        env:
          SPRING_PROFILES_ACTIVE: test
          AWS_ACCESS_KEYID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET: ${{ secrets.DEV_BUCKET_NAME }}