name: Build and Test CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3
      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      # Build and Test with Maven
      - name: Build with Maven
        run: mvn clean package --batch-mode
      # Run Tests
      - name: Run Tests
        run: mvn test